default:
  image: rikorose/gcc-cmake:gcc-8

stages:
  - build
  - test

job 1:
  stage: build
  before_script:
    - git submodule update --init --recursive
    - mkdir -p build
    - cd build
  script: 
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - ./scratch/gitlab_ci/gitlab_ci_example
  after_script:
    - cd $CI_BUILDS_DIR
    

