default:
    image: registry.gitlab.com/globalai/repo:latest

stages:
  - build
  - test

.prepare_build: &prepare_build
  before_script:
    - mkdir -p build
    - cd build
    - mkdir -p ccache
    - export CCACHE_DIR="$(pwd)/ccache"
    - ccache -M 500M
    - ccache -s

.upload_ccache: &upload_cache
  cache:
    key: master_key
    paths:
      - build/ccache
      - build/eigen_ext-prefix
      - build/googletest-prefix
      - build/fmt_ext-prefix
      - build/google_benchmark_ext-prefix


build:
  stage: build
  <<: *prepare_build
  script:
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j $nproc
    - ccache -s
    - ../script/run_tests.sh
  <<: *upload_cache


static analysis:
  stage: test
  when: manual
  <<: *prepare_build
  script:
    - mkdir scan_results
    - scan-build -o scan_results cmake .. -DCMAKE_BUILD_TYPE=Release
    - scan-build -o scan_results make -j $nproc
    - ccache -s
  artifacts:
    paths:
      - build/scan_results
    expire_in: 1 week
  <<: *upload_cache

coverage:
  stage: test
  only:
    refs:
      - master

  script:
    - ../script/run_coverage.sh
  artifacts:
    paths:
      - build/coverage
    expire_in: 1 week
  <<: *upload_cache

benchmarks:
  stage: test
  only:
    refs:
      - master
  <<: *prepare_build
  script:
    - cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_BENCHMARKS=ON
    - make -j $nproc
    - ./run_benchmarks
  artifacts:
    paths:
      - build/bench_results
  <<: *upload_cache
