default:
    image: registry.gitlab.com/globalai/repo:latest

stages:
  - build
  - test

static analysis:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - mkdir scan_results
    - scan-build -o scan_results cmake .. -DCMAKE_BUILD_TYPE=Release
    - scan-build -o scan_results make -j $nproc
    - ../script/run_tests.sh
  artifacts:
    paths:
      - build/scan_results
    expire_in: 1 week

coverage:
  stage: test
  when: manual
  script:
    - mkdir -p build
    - cd build
    - ../script/run_coverage.sh
  artifacts:
    paths:
      - build/coverage
    expire_in: 1 week
