default:
    image: superjax/ci:latest

stages:
  - build
  - test

job 1:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
  script: 
    - scan-build cmake .. -DCMAKE_BUILD_TYPE=Release
    - scan-build make
    - cd ..
    - ./script/run_tests.sh
  after_script:
    - cd $CI_BUILDS_DIR
    

