default:
  image: registry.gitlab.com/globalai/repo:latest

stages:
  - build
  - test

.prepare_build: &prepare_build
  before_script:
    - mkdir -p build
    - cd build
    - mkdir -p ccache
    - export CCACHE_DIR="$(pwd)/ccache"
    - export PATH=/usr/lib/ccache:$PATH
    - ccache -s

.upload_ccache: &upload_cache
  cache:
    key: master_key
    paths:
      - build/ccache
      - build/eigen_ext-prefix
      - build/googletest-prefix
      - build/fmt_ext-prefix
      - build/google_benchmark_ext-prefix
      - build/async_comm_ext-prefix
      - build/ext_ceres-prefix
      - build/google_gflags-prefix
      - build/google_glog-prefix
      - build/yaml_ext-prefix

.gtest_reports: &gtest_reports
  artifacts:
    when: always
    reports:
      junit:
        - build/**/*-report.xml

build_gcc:
  stage: build
  <<: *prepare_build
  <<: *upload_cache
  <<: *gtest_reports
  script:
    - CC=gcc CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j12 -l12
    - ccache -s
    - ../script/run_tests.sh

build_clang:
  stage: build
  <<: *prepare_build
  <<: *upload_cache
  <<: *gtest_reports
  script:
    - CC=clang CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j12 -l12
    - ccache -s
    - ../script/run_tests.sh

static analysis:
  stage: test
  allow_failure: true
  <<: *prepare_build
  <<: *upload_cache
  script:
    - mkdir scan_results
    - CC=gcc CXX=g++ scan-build -o scan_results cmake .. -DCMAKE_BUILD_TYPE=Release
    - CC=gcc CXX=g++ scan-build -o scan_results make -j12 -l12
    - ccache -s
  artifacts:
    paths:
      - build/scan_results
    expire_in: 1000 yrs

coverage:
  stage: test
  allow_failure: true
  <<: *prepare_build
  <<: *upload_cache
  script:
    - ../script/run_coverage.sh
  artifacts:
    paths:
      - build/coverage
    expire_in: 1000 yrs

benchmarks:
  stage: test
  allow_failure: true
  <<: *prepare_build
  <<: *upload_cache
  script:
    - CC=gcc CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_BENCHMARKS=ON
    - make -j12 -l12
    - ./run_benchmarks
  artifacts:
    paths:
      - build/bench_results
