default:
    image: registry.gitlab.com/globalai/repo:latest

stages:
  - build
  - test

.prepare_build: &prepare_build
  before_script:
    - mkdir -p build
    - cd build
    - mkdir -p ccache
    - export CC=gcc
    - export CXX=g++
    - export CCACHE_DIR="$(pwd)/ccache"
    - ccache -s

build:
  stage: build
  <<: *prepare_build
  script:
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j12 -l12
    - ccache -s
    - ../script/run_tests.sh


static analysis:
  stage: test
  allow_failure: true
  <<: *prepare_build
  script:
    - mkdir scan_results
    - scan-build -o scan_results cmake .. -DCMAKE_BUILD_TYPE=Release
    - scan-build -o scan_results make -j12 -l12
    - ccache -s
  artifacts:
    paths:
      - build/scan_results
    expire_in: 1000 yrs

coverage:
  stage: test
  allow_failure: true
  <<: *prepare_build
  script:
    - ../script/run_coverage.sh
  artifacts:
    paths:
      - build/coverage
    expire_in: 1000 yrs

benchmarks:
  stage: test
  allow_failure: true
  <<: *prepare_build
  script:
    - cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_BENCHMARKS=ON
    - make -j12 -l12
    - ./run_benchmarks
  artifacts:
    paths:
      - build/bench_results
