default:
  image: registry.gitlab.com/globalai/repo:latest

stages:
  - build
  - test

.prepare_build: &prepare_build
  before_script:
    - mkdir -p build
    - cd build
    - mkdir -p ccache
    - export CCACHE_DIR="/ccache"
    - export PATH=/usr/lib/ccache:$PATH
    - ccache -s

.gtest_reports: &gtest_reports
  artifacts:
    when: always
    reports:
      junit:
        - build/**/*-report.xml

build_gcc:
  stage: build
  <<: *prepare_build
  <<: *gtest_reports
  script:
    - CC=gcc CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j12 -l12
    - ccache -s
    - ../script/run_tests.sh

build_clang:
  stage: build
  <<: *prepare_build
  <<: *gtest_reports
  script:
    - CC=clang CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Release
    - make -j12 -l12
    - ccache -s
    - ../script/run_tests.sh

static analysis:
  stage: test
  allow_failure: true
  <<: *prepare_build
  script:
    - mkdir scan_results
    - CC=gcc CXX=g++ scan-build -o scan_results cmake .. -DCMAKE_BUILD_TYPE=Release
    - CC=gcc CXX=g++ scan-build -o scan_results make -j12 -l12
    - ccache -s
  artifacts:
    paths:
      - build/scan_results
    expire_in: 1000 yrs

coverage:
  stage: test
  allow_failure: true
  <<: *prepare_build
  script:
    - CC=gcc CXX=g++ cmake .. -DTEST_COVERAGE=ON
    - make -j12 -l12
    - gcovr -r .. --config ../script/gcovr.cfg --xml-pretty --output coverage.xml
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 1000 yrs
    reports:
      cobertura: build/coverage.xml

benchmarks:
  stage: test
  allow_failure: true
  <<: *prepare_build
  script:
    - CC=gcc CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_BENCHMARKS=ON
    - make -j12 -l12
    - ./run_benchmarks
  artifacts:
    paths:
      - build/bench_results
