default:
    image: registry.gitlab.com/globalai/repo:latest

stages:
  - build
  - test

static analysis:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - scan-build cmake .. -DCMAKE_BUILD_TYPE=Release
    - scan-build make -j
    - ../script/run_tests.sh

coverage:
  stage: test
  when: manual
  script:
    - mkdir -p build
    - cd build
    - ../script/run_coverage.sh
  artifacts:
    paths:
      - build/coverage
    expire_in: 1 week
