default:
  image: rikorose/gcc-cmake:gcc-8

stages:
  - build
  - test

job 1:
  stage: build
  before_script:
    - mkdir -p build
    - cd build
  script: 
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - make
    - cd ..
    - ./script/run_tests.sh
  after_script:
    - cd $CI_BUILDS_DIR
    

