# Initial State
use_init_sim_state: true
translation0: [0, 0, 0]
rotation0: [1, 0, 0, 0]
vel0: [0, 0, 0]
p_b2g0: [0, 0, 0]
lla0_deg: [40.246184, -111.647769, 1387.997511]
heading0_deg: 0

# Initial state covariance (sqrt of diagonal)
P0_stdev:
  translation: [0.0, 0.0, 0.0] # no uncertainty about origin
  rotation: [0.1, 0.1, 0.0] # no uncertainty about heading
  vel: [0.1, 0.1, 0.1]
  acc_bias: [0.1, 0.1, 1.0]
  gyro_bias: [0.1, 0.1, 0.1]
  gps_clk: [1.0, 1.0]
  gal_clk: [1.0, 1.0]
  glo_clk: [1.0, 1.0]
  p_b2g: [0.01, 0.01, 0.01]
  T_I2e: [1e-6, 1e-6, 3, 200, 200, 200] # rx, ry, rz, tx, ty, tz
  sd: 1.0

# Measurement Covariances (sqrt of diagonal)
point_pos_stdev: [1, 1, 3, 0.1, 0.1, 0.3]
gps_obs_stdev: [0.01, 0.01]
gal_obs_stdev: [0.01, 0.01]
glo_obs_stdev: [0.01, 0.01]
fix_and_hold_stdev: 0.001
imu_stdev:
  gyro: [0.01, 0.01, 0.01]
  accel: [0.1, 0.1, 0.1]

# Process noise covariance (sqrt of diagonal)
process_stdev:
  translation: [0, 0, 0]
  rotation: [0, 0, 0]
  vel: [0, 0, 0]
  acc_bias: [0.1, 0.1, 1.0]
  gyro_bias: [0.01, 0.01, 0.01]
  gps_clk: [0.1, 0.1]
  gal_clk: [0.1, 0.1]
  glo_clk: [0.1, 0.1]
  p_b2g: [0, 0, 0]
  T_I2e: [0, 0, 0, 0, 0, 0] # rx, ry, rz, tx, ty, tz
  sd: 0.001
