function(build_guard)
    file(TO_CMAKE_PATH "${PROJECT_BINARY_DIR}/CMakeLists.txt" LOC_PATH)
    if(EXISTS "${LOC_PATH}")
        file(REMOVE_RECURSE ${PROJECT_BINARY_DIR}/CMakeFiles)
        file(REMOVE ${PROJECT_BINARY_DIR}/CMakeCache.txt)
        file(REMOVE_RECURSE ${PROJECT_BINARY_DIR}/eigen_ext-prefix)
        file(REMOVE_RECURSE ${PROJECT_BINARY_DIR}/googletest-prefix)
        file(REMOVE_RECURSE ${PROJECT_BINARY_DIR}/clean)
        file(REMOVE_RECURSE ${PROJECT_BINARY_DIR}/run_tests)
        message(FATAL_ERROR "You cannot build in a source directory (or any directory with a CMakeLists.txt file). Please remove the CMakeFiles and CmakeCache.txt then navigate to the build directory.")
    endif()
endfunction()
